[tool.poetry]
name = "TodistusApp"
version = "0.1.0"
description = ""
authors = ["venlavanhala <venla.e.vanhala@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
cowsay = ">=6.1,<7.0"
invoke = ">=2.2.1,<3.0.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=8.4.2,<9.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
